### ISSUE TITLE
Lock screen forces the app to come into foreground on the phone

### ISSUE THREAD

**Issue by kshala-ford** [smartdevicelink/hello_sdl_android#1]
The Hello SDL example does not check if the app is in foreground or background (or even started by the user) on the phone. Therefore if the app is in background on the phone and the user starts the app on SYNC the line to start the lock screen activity will move the app to foreground on the phone.

This behaviour does not match the desired behaviour we require from App partners. The app should stay in background on the phone and start the lock screen activity only if the user moves the app to foreground (by starting it).

**Comment by NDNELSON** [comment]
I am developing an app for android and ford cars. I was using the applink library 2.0.

My apps works fine and it did not disconnect from the car system. I decided to update to 4.0 sdl library, but i have had a single problem . AFter single minutes the proxy closes and the app losses conection from the car system . My app consumes from 40bm to 110mb of ram. I am testing in samsung galaxy s6a nd my car register as TDK is a ford fiesta 2016
 titanium.
My code is based from hello sdl project.
 I read your post and my question is if this behaviour of the app when the proxy losses conection is because the notes you said

**Comment by kshala-ford** [comment]
Fixed with PR #2 
Closing as fixed
